import AuthHelper from "@/components/common/auth-helper"
import Navbar from "@/components/ui/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Navbar />
        {children}
        <AuthHelper/>
      </body>
    </html>
  )
}
